# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PgRcSiasDgZU7k6SwY37siMu5cUhp9Uc
"""

def do_e(row, graph):
  values = []
  current = ""
  for col in row:
    if (col != " " and col != "e"):
      current += col
    elif (col == " " and current != ""):
      values.append(int(current))
      current = ""
  values.append(int(current))
  if (values[0] not in graph):
    graph[values[0]] = []
  if (values[1] not in graph):
    graph[values[1]] = []
  if (values[1] not in graph[values[0]]):
    graph[values[0]].append(values[1])
  if (values[0] not in graph[values[1]]):
    graph[values[1]].append(values[0])
  return graph

def identify(tipo, row, graph):
  if (tipo == "e"):
    graph = do_e(row, graph)
  return graph

def cargar_matriz(route, graph):
  file = open(route, "r")
  for r in file: 
    graph = identify(r[0], r, graph)
  file.close()
  return graph

def setup_tandas(graph):
  tandas = []
  skip = []
  for item in graph.items():
    lavar = []
    lavar.append(item[0])
    if (item[0] in skip):
      continue
    for item2 in graph.items():
      if (item[0] != item2[0] and item2[0] not in item[1] and item2[0] not in skip):
        any_present = False
        for value in item2[1]:
          if (value in lavar):
            any_present = True
            break
        if (not any_present):
          lavar.append(item2[0])
          skip.append(item2[0])
    skip.append(item[0])
    tandas.append(lavar)
  return tandas

graph = {}
graph = cargar_matriz("/content/primer_problema.txt", graph)
tandas = setup_tandas(graph)
print(tandas)
f = open("entrega_1.txt", "w")
for i in range(0, len(tandas)):
  for value in tandas[i]:
    f.write(str(value) + " " + str(i+1) + "\n")
f.close()